[package]
name = "minimal-plonk"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ff = "0.4"
ark-ec = "0.4"
ark-poly = "0.4"
ark-poly-commit = "0.4"
ark-bn254 = { version = "0.4", optional = true }
ark-bls12-381 = { version = "0.4", optional = true }
ark-std = "0.4"
ark-serialize = { version = "0.4", features = ["derive"] }
blake2 = "0.10"
merlin = "3"
rand = "0.8"
sha2 = "0.10"
thiserror = "1"

[dev-dependencies]
criterion = "0.5"

[features]
default = ["bn254"]
bn254 = ["dep:ark-bn254"]
bls12_381 = ["dep:ark-bls12-381"]

[[bench]]
name = "micro_fft"
harness = false

[[bench]]
name = "micro_kzg"
harness = false

[[bench]]
name = "micro_pairing"
harness = false

[[bench]]
name = "macro_plonk"
harness = false
